import { TypeProduct, enumBlindBoxNFTType } from 'src/types/product-types';

export const dummyProducts: Array<TypeProduct> = [
    {
        tokenId: '0',
        image: '/assets/images/blindbox/blindbox-nft-template1.png',
        name: 'Project Title',
        price_ela: 199,
        price_usd: 88,
        likes: 10,
        views: 100,
        sold: 24,
        author: 'nickName',
        type: enumBlindBoxNFTType.ComingSoon,
        endTime: '2022/02/28 10:00',
        authorDescription: '--',
        authorImg: '--',
        authorAddress: '--',
        description: '--',
        tokenIdHex: '--',
        royalties: 0,
        createTime: '--',
        holderName: '--',
        holder: '--',
        isLike: false,
    },
    {
        tokenId: '1',
        image: '/assets/images/blindbox/blindbox-nft-template2.png',
        name: 'Project Title',
        price_ela: 199,
        price_usd: 88,
        likes: 10,
        views: 100,
        sold: 24,
        author: 'nickName',
        type: enumBlindBoxNFTType.SaleEnds,
        endTime: '2022/02/28 10:00',
        authorDescription: '--',
        authorImg: '--',
        authorAddress: '--',
        description: '--',
        tokenIdHex: '--',
        royalties: 0,
        createTime: '--',
        holderName: '--',
        holder: '--',
        isLike: false,
    },
    {
        tokenId: '2',
        image: '/assets/images/blindbox/blindbox-nft-template3.png',
        name: 'Project Title',
        price_ela: 199,
        price_usd: 88,
        likes: 10,
        views: 100,
        sold: 24,
        author: 'nickName',
        type: enumBlindBoxNFTType.SaleEnded,
        authorDescription: '--',
        authorImg: '--',
        authorAddress: '--',
        description: '--',
        tokenIdHex: '--',
        royalties: 0,
        createTime: '--',
        holderName: '--',
        holder: '--',
        isLike: false,
    },
    {
        tokenId: '3',
        image: '/assets/images/blindbox/blindbox-nft-template4.png',
        name: 'Project Title',
        price_ela: 199,
        price_usd: 88,
        likes: 10,
        views: 100,
        sold: 24,
        author: 'nickName',
        type: enumBlindBoxNFTType.ComingSoon,
        endTime: '2022/02/28 10:00',
        authorDescription: '--',
        authorImg: '--',
        authorAddress: '--',
        description: '--',
        tokenIdHex: '--',
        royalties: 0,
        createTime: '--',
        holderName: '--',
        holder: '--',
        isLike: false,
    },
    {
        tokenId: '4',
        image: '/assets/images/blindbox/blindbox-nft-template5.png',
        name: 'Project Title',
        price_ela: 199,
        price_usd: 88,
        likes: 10,
        views: 100,
        sold: 24,
        author: 'nickName',
        type: enumBlindBoxNFTType.SaleEnds,
        endTime: '2022/02/28 10:00',
        authorDescription: '--',
        authorImg: '--',
        authorAddress: '--',
        description: '--',
        tokenIdHex: '--',
        royalties: 0,
        createTime: '--',
        holderName: '--',
        holder: '--',
        isLike: false,
    },
    {
        tokenId: '5',
        image: '/assets/images/blindbox/blindbox-nft-template2.png',
        name: 'Project Title',
        price_ela: 199,
        price_usd: 88,
        likes: 10,
        views: 100,
        sold: 24,
        author: 'nickName',
        type: enumBlindBoxNFTType.SaleEnded,
        authorDescription: '--',
        authorImg: '--',
        authorAddress: '--',
        description: '--',
        tokenIdHex: '--',
        royalties: 0,
        createTime: '--',
        holderName: '--',
        holder: '--',
        isLike: false,
    },
    {
        tokenId: '6',
        image: '/assets/images/blindbox/blindbox-nft-template1.png',
        name: 'Project Title',
        price_ela: 199,
        price_usd: 88,
        likes: 10,
        views: 100,
        sold: 24,
        author: 'nickName',
        type: enumBlindBoxNFTType.ComingSoon,
        endTime: '2022/02/28 10:00',
        authorDescription: '--',
        authorImg: '--',
        authorAddress: '--',
        description: '--',
        tokenIdHex: '--',
        royalties: 0,
        createTime: '--',
        holderName: '--',
        holder: '--',
        isLike: false,
    },
];
